# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '844c93c58ad77961ca2af80ed16b5e7a233d4c35044fa86a0830761d290602c6'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack