# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.396.node.bone] at @s run function animated_java:396/variants/birch/zzz/apply_to_node_bone
execute on passengers if entity @s[tag=aj.396.node.carpet] at @s run function animated_java:396/variants/birch/zzz/apply_to_node_carpet
return 1